### ISSUE TITLE
Show current version numbers for releases

### ISSUE THREAD

**Issue by pahy** [TYPO3-infrastructure/get.typo3.org#15]
Hi folks!
Thanks for your awesome work, i like it.
I would like to suggest a little extension, which could be adapted from the legacy download page. There was a quick information about the latest version number and its release date. It is much easier than clicking twice to get to the release notes, to see if there is a newer release.
Regards,
Patrick

**Comment by psychomieze** [comment]
Hey,

thanks for your suggestion, I added the latest version and release date on the home page of get.typo3.org :)
