### ISSUE TITLE
Overview about releases

### ISSUE THREAD

**Issue by sbusemann** [TYPO3-infrastructure/get.typo3.org#17]
As a sysadmin of a TYPO3 installation, I like to get a quick overview about TYPO3 minor releases. I want check, when was the last security release. 

Atm i get only the latest version and i get no overview (list view) of all releases of a major version.

**Comment by psychomieze** [comment]
From any major version page choose the link "See all releases" from the link list (for example on https://get.typo3.org/version/8 ) -> https://get.typo3.org/list/version/8 << is that enough for you? ;)
