### ISSUE TITLE
. htacces file in Typo3 9.5.0 Zip/Gz File is missing

### ISSUE THREAD

**Issue by sbusemann** [TYPO3-infrastructure/get.typo3.org#29]
Dear Sir or Madam

In the New zip/gz File with Typo3 Version 9.5.0 is the .htaccess File missinig. Is this normal?

Report via OTRS: Ticket#20181007609000118

**Comment by ohader** [comment]
Related to https://review.typo3.org/#/c/58451/
`.htaccess` and `web.config` are created in install tool - thus previous `_.htaccess` file in root-folder of release package is not there anymore.

**Comment by Teisi** [comment]
I run into the same problem - so, would it not be good if in the install tool in the description stand where the files are? e.g. at the "BE.versionNumberInFilename" description. Cause i think "newcomers" won't find them, like me... :)
