### ISSUE TITLE
JSON view sends wrong headers

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3-infrastructure/get.typo3.org#3]
1. Go to https://get.typo3.org/json
1. Look at the headers: `content-type: text/html; charset=UTF-8`

Should be: `content-type: application/json`
Charset is by default UTF-8, so it can be removed, see: http://www.ietf.org/rfc/rfc4627.txt

**Comment by spoonerWeb** [comment]
Seems that my patch didn't resolve it.

**Comment by psychomieze** [comment]
I'll take a look next week probably - or any other contribution / patches are welcome.

**Comment by psychomieze** [comment]
Server answers now with:

```< HTTP/1.1 200 OK
< Server: nginx/1.13.6
< Date: Sat, 24 Mar 2018 17:47:40 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=0, must-revalidate, private
< X-Content-Type-Options: nosniff
< Referrer-Policy: no-referrer, strict-origin-when-cross-origin
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload;
```

looks good to me.
