### ISSUE TITLE
Dead links on release notes

### ISSUE THREAD

**Issue by SimonWpt** [TYPO3-infrastructure/get.typo3.org#30]
At the end of the release notes TYPO3 6, i.e. https://get.typo3.org/release-notes/6.2.31 the link of `Download GPG signed release README.md file` lead to an error: https://typo3.azureedge.net/typo3/6.2.31/README.md

**Comment by ohader** [comment]
That's the same for other older versions (e.g. https://get.typo3.org/release-notes/6.2.0).
At that time GPG-signing has not been used yet for TYPO3 releases.
