### ISSUE TITLE
v8: Browser requirements for backend

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-infrastructure/get.typo3.org#32]
Hey,

we just had an editor that is not able to put a link onto an image in IE11.
I can reproduce this - instead of on the image, the link gets prepended to the text.

I think it boils down to ckeditor not fully supporting IE11:
https://github.com/ckeditor/ckeditor5/issues/330

I think it would be good to note that IE11 might have shortcomings in the backend in 
https://get.typo3.org/version/8

We need to teach clients to use other browsers anyway... In this case it is a municipality but I am trying to convince their IT that they should supply another browser to their employees.

**Comment by bmack** [comment]
Hey Jonas,

thanks for your feedback. However, the issue you're pointing to is to "CKEditor 5", however TYPO3 v8/v9 is packaging CKEditor4, which supports IE11 AFAIK.

**Comment by jonaseberle** [comment]
Hey Benni, thank you. :man_facepalming: 

I cross-checked in another v8 instance with ckeditor. The actual problem is putting a link on an image - the link gets put at the very beginning of the content instead of around the image. No JavaScript error, though. 

----
IE11 will be phased out at the German state BaWü in 10 months (they still dare to do so ;) some web applications are supposedly not ready yet).

**Comment by bmack** [comment]
Hi Jonas. well, if you have ckeditor with the image plugin enabled, that should be within the ckeditor-image TYPO3 extension then, right?

**Comment by jonaseberle** [comment]
I can also reproduce without rte_ckeditor_image, just taking 
```
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Full.yaml" }

editor:
  config:
    # RTE default config removes image plugin - restore it:
    removePlugins: null
```
I have checked with a 8.7.25-dev, with and without rte_ckeditor_image installation according to https://github.com/netresearch/t3x-rte_ckeditor_image and I cannot put links onto images...

After playing around a bit, it looks like this:
![grafik](https://user-images.githubusercontent.com/1678001/53579759-736bbc00-3b7a-11e9-97ad-d2836d10f79b.png)

**Comment by bmack** [comment]
Hey Jonas,

so, this is more a core issue than an issue on get.typo3.org then. Could you file an issue on https://forge.typo3.org/projects/typo3cms-core/issues ? 

Thanks!
