### ISSUE TITLE
Download-Page: Missing the infos of TYPO3-Extensions not part of minimal version 

### ISSUE THREAD

**Issue by Padina42** [TYPO3-infrastructure/get.typo3.org#33]
The Download-page of typo3.org contains not all required informations about the download. 

https://get.typo3.org/version/9

Using that page, I wont't find informations about the extension typo3/cms-tstemplate, if i use the composer-variation 
composer require typo3/minimal

I had a diskussion about that in the german mailing-list.

Dieter

**Comment by susannemoog** [comment]
Please check again, we adjusted information on composer download.

**Comment by susannemoog** [comment]
Please reopen if the issue persists.
