### ISSUE TITLE
Fix unsafe download links -> explicit https

### ISSUE THREAD

**Issue by thomaszbz** [TYPO3-infrastructure/get.typo3.org#41]
Hi, please prefix all the download links with https:// 

Example: https://get.typo3.org/version/8

E.g. change

`wget --content-disposition get.typo3.org/8`
to
`wget --content-disposition https://get.typo3.org/8`

Please keep in mind that it is _not_ sufficient to 301-redirect the resource to a https-secured url. The server does this already, but it is pretty much pointless in a MITM scenario. Reason: When a MITM comes into play, then the attacker will have control over what is responded to the user's request. The attacker will then just not send the 301 and instead respond with a compromised download. Or the attacker will send a 301 pointing to a compromised download.

301ing itself is not an issue as long as the chain of redirects does not leave https.

Hint: I am aware that users _should_ check ckecksums anyways. It's just that if they do that, that's a different story.

**Comment by bmack** [comment]
Fixed. Thanks for the report

**Comment by thomaszbz** [comment]
@bmack there's more download URIs which need the https prefix. E.g. 

`curl -L -o typo3_src.tgz get.typo3.org/8`

Hint: The text "when wget fails with SSL error" is just there because wget had issues with SNI a long time ago (see comment below). curl is _still_ checking if the certificate is valid. So the whole link can be https-secured as well. It would be 301-redirected anyways, so this can never be meant as a fallback towards http.
