### ISSUE TITLE
Statement on download page installs version 9 instead of 10

### ISSUE THREAD

**Issue by mz-aimcom** [TYPO3-infrastructure/get.typo3.org#42]
The composer statement on the official download page (https://get.typo3.org/version/10) will install a TYPO3 v9 instead of v10.

`composer create-project typo3/cms-base-distribution my-new-project`

```
~/typo3-10-or-9$ composer create-project typo3/cms-base-distribution typo3-10-or-9
Installing typo3/cms-base-distribution (v9.5.0)
```

https://github.com/TYPO3-infrastructure/get.typo3.org/blob/e37039b571e13ee5fb9684f109f9f627f3865b86/templates/default/partials/download-area.html.twig#L46

**Comment by susannemoog** [comment]
That was because the base distribution was not yet updated. It is now and the command now installs v10:

``` 
$: composer create-project typo3/cms-base-distribution my-new-project
Installing typo3/cms-base-distribution (v10.0.0)
  - Installing typo3/cms-base-distribution (v10.0.0): Downloading (100%)
```
