### ISSUE TITLE
[FEATURE][IMPROVEMENT] skip the hero image in the download page

### ISSUE THREAD

**Issue by erredeco** [TYPO3-infrastructure/get.typo3.org#5]
When clicking on the button "get version 8" you are redirected to the page https://get.typo3.org/version/8; it should be nice, in my opinion, to point directly to the section of the page where the dowloads are (i.e. to jump directly to the content of the page - something like https://get.typo3.org/version/8#content) skipping the hero image. I hope I made myself clear
What do you think?

**Comment by psychomieze** [comment]
Hey Riccardo, for now I made the header image a lot smaller. Can you check again if that's better for you?

**Comment by erredeco** [comment]
Hi Susi; mine was just a suggestion :) 

I attach a screenshot of what I see using my MAC (1440x900px). I think that it is still a bit difficult for the user to understand where exactly TYPO3 should be downloaded. What is your opinion?

Said that, for me the reduced header is fine :) Feel free to close this issue.

![schermata 2018-03-24 alle 18 53 22](https://user-images.githubusercontent.com/3647646/37867168-be249048-2f94-11e8-8532-12f035f3e86d.png)
