### ISSUE TITLE
Update wording about TYPO3 v10 LTS

### ISSUE THREAD

**Issue by schams-net** [TYPO3-infrastructure/get.typo3.org#54]
The landing page shows details about the upcoming TYPO3 v10 LTS release. However, the current wording is pretty bad if you address people worldwide.

> _The upcoming LTS 10 release is scheduled for spring 2020._

April is not "Spring" in all parts if the world. For us (in Australia for example), it's Autumn. Welcome to the [Southern Hemisphere](https://en.wikipedia.org/wiki/Southern_Hemisphere).

**Comment by schams-net** [comment]
Updated wording (as discussed with and confirmed by Heather McNamee):

> _TYPO3 v10 LTS is scheduled to be released in April 2020. Updates and security fixes will be provided for three years starting from the release date. We encourage users and agencies to install and use the v10 sprint releases until the LTS release is available. Further details about the releases and release dates are available in the roadmap._

**Comment by bmack** [comment]
👍

**Comment by bmack** [comment]
would you care to create a PR for this?
