### ISSUE TITLE
TYPO3\CMS\Frontend\Controller\ErrorController::unavailableAction() must implement interface Psr\Http\Message\ServerRequestInterface, null given

### ISSUE THREAD

**Issue by bibusdax** [TYPO3-infrastructure/get.typo3.org#59]
Since 9.5.11 I have my log full of the following error:

Core: Exception handler (CLI): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Frontend\Controller\ErrorController::unavailableAction() must implement interface Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/clients/client1/web1/web/typo3_src-9.5.11-patched/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php on line 2674 | TypeError thrown in file /var/www/clients/client1/web1/web/typo3_src-9.5.11-patched/typo3/sysext/frontend/Classes/Controller/ErrorController.php in line 46

**Comment by susannemoog** [comment]
Hey,

this is the issue tracker for the web site get.typo3.org - for issues with TYPO3 please check https://forge.typo3.org/projects/typo3cms-core/issues
